name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- #$NUMBER - $TITLE (@$AUTHOR)'
categories:
  - title: "⚠ Breaking Changes"
    labels:
      - 'breaking-change'
  - title: '⬆️ Dependencies and CI'
    collapse-after: 1
    labels:
      - 'dependencies'
      - 'ci'
template: |
  ## What’s Changed

  $CHANGES
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'new-feature'
      - 'enhancement'
  default: patch
